### ISSUE TITLE
Should `fractionalDigits` be called `fractionalSecondDigits` instead?

### ISSUE THREAD

**Issue by longlho** [tc39/proposal-intl-duration-format#177]
To be consistent with `Intl.DateTimeFormat`?

**Comment by ben-allen** [comment]
`fractionalDigits` has that name because `"seconds"` isn't the only unit that can have associated fractional digits. For example, if milliseconds is the largest unit displayed in the `"numeric"` style, then the fractional digits representing microseconds and nanoseconds will get appended to milliseconds, not to seconds.

**Comment by longlho** [comment]
Gotcha thanks!
