### ISSUE TITLE
Difference from Sequence unit formatting?

### ISSUE THREAD

**Issue by rxaviers** [tc39/proposal-intl-duration-format#5]
Let's clarify the reason why we need DurationFormat and can't use https://github.com/tc39/ecma402/issues/398

**Comment by younies** [comment]
DurationFormat can use some functionality of sequence unit formatting. However, there are many operations on DurationFormat that could not be added to sequence unit formatting such as:
  * Hide zero values
  * Hide tailer zero values
  * Hide  zero values in the beginning 
  * Approximation with some specifications
  *  ... etc.

Those features can be added to sequence unit formatting, but I do not think we need to add those functionalities that does not make sense for most of the unit formatting.

In the end, I think we need to discuss this in the EcmaScript meeting.

**Comment by sffc** [comment]
Here are three reasons why I feel Intl.DurationFormat deserves its own class:

1. Temporal.Duration will be a first-class type, and it deserves a first-class formatting interface.  It does not make sense to pass Temporal.Duration into Intl.NumberFormat, since the settings for Intl.NumberFormat might not align with a duration.
2. Intl.RelativeTimeFormat is precedent in ECMA-402 for a class that is a hybrid between datetime formatting and number formatting.  Relative time formatting also could have fit into one of the two existing classes, but we decided to keep it separate.
3. The process of formatting durations has unique requirements, which do not easily generalize to other types of sequence units:
    1. The "numeric" style, like `05:00`
    2. Specifying a set of fields to display among the Temporal.Duration fields (including how to handle leading and trailing zeros)

**Comment by sffc** [comment]
Related: https://github.com/tc39/proposal-temporal/issues/533

**Comment by sffc** [comment]
To be clear, the "numeric" style for duration could also be applied in a slightly different form to:

1. Latitude and Longitude: `0° 0' 0'' N`
2. Feet and inches: `5' 1''`

There may be other examples of specific sets of units that have an additional form besides spelling out the unit name.

However, the existence of these related formats does not change my opinion on Intl.DurationFormat holding its own case for being a first-class type.

**Comment by younies** [comment]
Thanks @rxaviers for bringing this up.

As @sffc  mentioned and also we have added more need for `DurationFormat` class last meeting. Therefore, I will close this issue.

For info: [bit.ly/tc39-intl-duration-format ](bit.ly/tc39-intl-duration-format)

In the meantime, feel free to ask further questions about this topic.

**Comment by rxaviers** [comment]
My grasp from it is:
- `DurationFormat` doesn't provide any additional value compared to sequence unit format **in terms of i18n**
- The added value of DurationFormat is convenience compared to using sequence unit format for the use case of formatting time durations, because it will take care of doing time calculations
- The justification to include a first-class type DurationFormat for such specific use case is because we also have first-class type Temporal.Duration.

Though, it's still not clear to me why we need such specific class. Doesn't this proposal compete with sequence unit formatting + smart units? From what I understood, an equivalent DurationFormat would look something like this:

```js
new Intl.NumberFormat(undefined, {
  style: "unit",
  unit: "hour-and-minutes-and-seconds"
}).format(1.777);
// "1 hour, 46 minutes, and 40 seconds" (en-US)
```

**Comment by sffc** [comment]
@rxaviers What are your thoughts on my three points in https://github.com/tc39/proposal-intl-duration-format/issues/5#issuecomment-620742426?

> * `DurationFormat` doesn't provide any additional value compared to sequence unit format **in terms of i18n**

It does, though: the numeric format isn't available through sequence units.

> * The added value of DurationFormat is convenience compared to using sequence unit format for the use case of formatting time durations, because it will take care of doing time calculations

Intl.DurationFormat doesn't perform calculations (#10), but it has convenience options that don't necessarily apply when not formatting durations.

> * The justification to include a first-class type DurationFormat for such specific use case is because we also have first-class type Temporal.Duration.
> 
> Though, it's still not clear to me why we need such specific class. Doesn't this proposal compete with sequence unit formatting + smart units? From what I understood, an equivalent DurationFormat would look something like this:
> 
> ```js
> new Intl.NumberFormat(undefined, {
>   style: "unit",
>   unit: "hour-and-minutes-and-seconds"
> }).format(1.777);
> // "1 hour, 46 minutes, and 40 seconds" (en-US)
> ```

If you already have a Temporal.Duration, how do you format it with the sequence unit model? We could add it as an acceptable argument to Intl.NumberFormat.prototype.format, but then you have weird cases like what happens if the requested units are not time units, etc.
